server:
  port: 8080
logging:
  pattern:
    console: |
      {"timestamp": "%d{yyyy-MM-dd HH:mm:ss.SSS}","level": "%p","thread": "%t","clazz": "%logger{36}","transactionId": "%X{X-Trace-Id}","payload": %msg}
    file: |
      {"timestamp": "%d{yyyy-MM-dd HH:mm:ss.SSS}","level": "%p","thread": "%t","clazz": "%logger{36}","transactionId": "%X{X-Trace-Id}","payload": %msg}
  level:
    root: INFO
    org.springframework.data.r2dbc: INFO
  file:
    name: log.log
spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///testDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: testDb
    username: sa
    password:

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password:
    drop-first: true
  h2:
    console.enabled: true
